# Generated by Django 4.0.1 on 2022-05-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_alter_incident_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=20, default='0', max_digits=30),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=20, default='0', max_digits=30),
        ),
    ]
